### ISSUE TITLE
无法正常启用, macOS Sequoia 15.0 系统设置扩展中 Finder 扩展 没有找到SwiftMenu选项

### ISSUE THREAD

**Issue by NoirVoider** [lexrus/SwiftyMenu#2]
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/472daacd-5122-4218-966f-f06156f1eeba">

**Comment by travisbikkle** [comment]
同上。大家有没有发现macos15能用的？艾特我一下，谢谢

**Comment by bigbigpeng3** [comment]
找不到

**Comment by lexrus** [comment]
macOS 15.0 不展示第三方 Finder Sync 插件了，官方说 15.2 才会修好。我先实现了一个临时修复的版本。

https://forums.developer.apple.com/forums/thread/756711?answerId=812519022#812519022
